FROM golang

RUN go get github.com/jinzhu/gorm && \
    go get google.golang.org/grpc && \
    go get github.com/dgrijalva/jwt-go && \
    go get github.com/Sirupsen/logrus && \
    go get golang.org/x/time/rate && \
    go get github.com/gorilla/mux && \
    go get github.com/gorilla/handlers && \
    go get github.com/urfave/negroni && \
    go get github.com/satori/go.uuid && \ 
    go get github.com/jinzhu/gorm/dialects/postgres && \
    go get github.com/gkarlik/quark-go && \    
    go get -d github.com/gkarlik/expense-tracker/shared

COPY . /go/src/github.com/gkarlik/expense-tracker/api-gateway
WORKDIR /go/src/github.com/gkarlik/expense-tracker/api-gateway

ENV GATEWAY_NAME=ApiGateway \
    GATEWAY_VERSION=v1 \
    GATEWAY_PORT=9999 \
    GATEWAY_SECRET=mysecret \
    DISCOVERY=localhost:9999   

ENTRYPOINT go run main.go