// Code generated by protoc-gen-go.
// source: user-service/v1/user-service.proto
// DO NOT EDIT!

/*
Package proxy is a generated protocol buffer package.

It is generated from these files:
	user-service/v1/user-service.proto

It has these top-level messages:
	RegisterUserRequest
	RegisterUserResponse
	AuthenticateUserRequest
	AuthenticateUserResponse
*/
package proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterUserRequest struct {
	FirstName string `protobuf:"bytes,1,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=LastName" json:"LastName,omitempty"`
	Login     string `protobuf:"bytes,3,opt,name=Login" json:"Login,omitempty"`
	Password  string `protobuf:"bytes,4,opt,name=Password" json:"Password,omitempty"`
	Pin       string `protobuf:"bytes,5,opt,name=Pin" json:"Pin,omitempty"`
}

func (m *RegisterUserRequest) Reset()                    { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()               {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterUserRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterUserRequest) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type RegisterUserResponse struct {
	VerificationLink string `protobuf:"bytes,1,opt,name=VerificationLink" json:"VerificationLink,omitempty"`
}

func (m *RegisterUserResponse) Reset()                    { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()               {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterUserResponse) GetVerificationLink() string {
	if m != nil {
		return m.VerificationLink
	}
	return ""
}

type AuthenticateUserRequest struct {
	Login    string `protobuf:"bytes,1,opt,name=Login" json:"Login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
	Pin      string `protobuf:"bytes,5,opt,name=Pin" json:"Pin,omitempty"`
}

func (m *AuthenticateUserRequest) Reset()                    { *m = AuthenticateUserRequest{} }
func (m *AuthenticateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthenticateUserRequest) ProtoMessage()               {}
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthenticateUserRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthenticateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthenticateUserRequest) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type AuthenticateUserResponse struct {
	Login     string `protobuf:"bytes,1,opt,name=Login" json:"Login,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=LastName" json:"LastName,omitempty"`
}

func (m *AuthenticateUserResponse) Reset()                    { *m = AuthenticateUserResponse{} }
func (m *AuthenticateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthenticateUserResponse) ProtoMessage()               {}
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthenticateUserResponse) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthenticateUserResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AuthenticateUserResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterUserRequest)(nil), "RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "RegisterUserResponse")
	proto.RegisterType((*AuthenticateUserRequest)(nil), "AuthenticateUserRequest")
	proto.RegisterType((*AuthenticateUserResponse)(nil), "AuthenticateUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := grpc.Invoke(ctx, "/UserService/RegisterUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error) {
	out := new(AuthenticateUserResponse)
	err := grpc.Invoke(ctx, "/UserService/AuthenticateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/AuthenticateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AuthenticateUser(ctx, req.(*AuthenticateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserService_RegisterUser_Handler,
		},
		{
			MethodName: "AuthenticateUser",
			Handler:    _UserService_AuthenticateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-service/v1/user-service.proto",
}

func init() { proto.RegisterFile("user-service/v1/user-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0xc4, 0xa8, 0x1d, 0x3d, 0x84, 0x35, 0xe2, 0x1a, 0x3c, 0xc8, 0x9e, 0x44, 0x30,
	0x45, 0x3d, 0x7b, 0xb0, 0x07, 0x41, 0x08, 0x52, 0x22, 0x7a, 0x10, 0x3c, 0xc4, 0x3a, 0xd6, 0x55,
	0xdc, 0x8d, 0xbb, 0x9b, 0xaa, 0x9f, 0xc3, 0x83, 0x5f, 0x57, 0xf2, 0xc7, 0x9a, 0xd8, 0xc4, 0xde,
	0xf2, 0xde, 0x30, 0x93, 0xdf, 0xbc, 0x59, 0x60, 0x99, 0x46, 0x75, 0xa0, 0x51, 0x4d, 0xf9, 0x18,
	0x07, 0xd3, 0xc3, 0x41, 0x5d, 0x87, 0xa9, 0x92, 0x46, 0xb2, 0x4f, 0x0b, 0x36, 0x62, 0x9c, 0x70,
	0x6d, 0x50, 0x5d, 0x69, 0x54, 0x31, 0xbe, 0x66, 0xa8, 0x0d, 0xd9, 0x81, 0xfe, 0x19, 0x57, 0xda,
	0x5c, 0x24, 0x2f, 0x48, 0xad, 0x5d, 0x6b, 0xaf, 0x1f, 0xff, 0x1a, 0x24, 0x80, 0xd5, 0x28, 0xa9,
	0x8a, 0x76, 0x51, 0x9c, 0x69, 0xe2, 0x83, 0x1b, 0xc9, 0x09, 0x17, 0xd4, 0x29, 0x0a, 0xa5, 0xc8,
	0x3b, 0x46, 0x89, 0xd6, 0x6f, 0x52, 0xdd, 0xd3, 0xa5, 0xb2, 0xe3, 0x47, 0x13, 0x0f, 0x9c, 0x11,
	0x17, 0xd4, 0x2d, 0xec, 0xfc, 0x93, 0x0d, 0xc1, 0x6f, 0x42, 0xe9, 0x54, 0x0a, 0x8d, 0x64, 0x1f,
	0xbc, 0x6b, 0x54, 0xfc, 0x81, 0x8f, 0x13, 0xc3, 0xa5, 0x88, 0xb8, 0x78, 0xae, 0xe0, 0xe6, 0x7c,
	0x76, 0x0b, 0x5b, 0xa7, 0x99, 0x79, 0x44, 0x61, 0x72, 0x17, 0xeb, 0xcb, 0xcd, 0x10, 0xad, 0x2e,
	0x44, 0x7b, 0x21, 0xe2, 0x13, 0xd0, 0xf9, 0xf1, 0x15, 0x66, 0xfb, 0xfc, 0x46, 0xa4, 0xf6, 0x7f,
	0x91, 0x3a, 0xcd, 0x48, 0x8f, 0xbe, 0x2c, 0x58, 0xcb, 0x7f, 0x70, 0x59, 0x9e, 0x8e, 0x9c, 0xc0,
	0x7a, 0x3d, 0x1e, 0xe2, 0x87, 0x2d, 0x27, 0x0c, 0x36, 0xc3, 0xb6, 0x0c, 0x59, 0x8f, 0x9c, 0x83,
	0xf7, 0x17, 0x9d, 0xd0, 0xb0, 0x23, 0xac, 0x60, 0x3b, 0xec, 0xda, 0x93, 0xf5, 0x86, 0x2b, 0x37,
	0x6e, 0xaa, 0xe4, 0xfb, 0xc7, 0xdd, 0x72, 0xf1, 0x9c, 0x8e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xb2, 0xe9, 0x3f, 0x6e, 0x74, 0x02, 0x00, 0x00,
}
