// Code generated by protoc-gen-go.
// source: expense-service/v1/expense-service.proto
// DO NOT EDIT!

/*
Package proxy is a generated protocol buffer package.

It is generated from these files:
	expense-service/v1/expense-service.proto

It has these top-level messages:
	UserPagingRequest
	ExpensesReponse
	CategoriesReponse
	ExpenseRequest
	ExpenseResponse
	ExpenseIDRequest
	DeleteExpenseResponse
	CategoryRequest
	CategoryResponse
	CategoryIDRequest
	DeleteCategoryResponse
*/
package proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserPagingRequest struct {
	UserID uint32 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=Offset" json:"Offset,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=Limit" json:"Limit,omitempty"`
}

func (m *UserPagingRequest) Reset()                    { *m = UserPagingRequest{} }
func (m *UserPagingRequest) String() string            { return proto.CompactTextString(m) }
func (*UserPagingRequest) ProtoMessage()               {}
func (*UserPagingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserPagingRequest) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserPagingRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *UserPagingRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ExpensesReponse struct {
	Expenses []*ExpenseResponse `protobuf:"bytes,1,rep,name=Expenses" json:"Expenses,omitempty"`
}

func (m *ExpensesReponse) Reset()                    { *m = ExpensesReponse{} }
func (m *ExpensesReponse) String() string            { return proto.CompactTextString(m) }
func (*ExpensesReponse) ProtoMessage()               {}
func (*ExpensesReponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExpensesReponse) GetExpenses() []*ExpenseResponse {
	if m != nil {
		return m.Expenses
	}
	return nil
}

type CategoriesReponse struct {
	Categories []*CategoryResponse `protobuf:"bytes,1,rep,name=Categories" json:"Categories,omitempty"`
}

func (m *CategoriesReponse) Reset()                    { *m = CategoriesReponse{} }
func (m *CategoriesReponse) String() string            { return proto.CompactTextString(m) }
func (*CategoriesReponse) ProtoMessage()               {}
func (*CategoriesReponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CategoriesReponse) GetCategories() []*CategoryResponse {
	if m != nil {
		return m.Categories
	}
	return nil
}

type ExpenseRequest struct {
	ID       uint32           `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Date     int64            `protobuf:"varint,2,opt,name=Date" json:"Date,omitempty"`
	Value    float32          `protobuf:"fixed32,3,opt,name=Value" json:"Value,omitempty"`
	Category *CategoryRequest `protobuf:"bytes,4,opt,name=Category" json:"Category,omitempty"`
	UserID   uint32           `protobuf:"varint,5,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *ExpenseRequest) Reset()                    { *m = ExpenseRequest{} }
func (m *ExpenseRequest) String() string            { return proto.CompactTextString(m) }
func (*ExpenseRequest) ProtoMessage()               {}
func (*ExpenseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ExpenseRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ExpenseRequest) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *ExpenseRequest) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *ExpenseRequest) GetCategory() *CategoryRequest {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *ExpenseRequest) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type ExpenseResponse struct {
	ID       uint32            `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Date     int64             `protobuf:"varint,2,opt,name=Date" json:"Date,omitempty"`
	Value    float32           `protobuf:"fixed32,3,opt,name=Value" json:"Value,omitempty"`
	Category *CategoryResponse `protobuf:"bytes,4,opt,name=Category" json:"Category,omitempty"`
}

func (m *ExpenseResponse) Reset()                    { *m = ExpenseResponse{} }
func (m *ExpenseResponse) String() string            { return proto.CompactTextString(m) }
func (*ExpenseResponse) ProtoMessage()               {}
func (*ExpenseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExpenseResponse) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ExpenseResponse) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *ExpenseResponse) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *ExpenseResponse) GetCategory() *CategoryResponse {
	if m != nil {
		return m.Category
	}
	return nil
}

type ExpenseIDRequest struct {
	ID uint32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *ExpenseIDRequest) Reset()                    { *m = ExpenseIDRequest{} }
func (m *ExpenseIDRequest) String() string            { return proto.CompactTextString(m) }
func (*ExpenseIDRequest) ProtoMessage()               {}
func (*ExpenseIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ExpenseIDRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteExpenseResponse struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *DeleteExpenseResponse) Reset()                    { *m = DeleteExpenseResponse{} }
func (m *DeleteExpenseResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteExpenseResponse) ProtoMessage()               {}
func (*DeleteExpenseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteExpenseResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CategoryRequest struct {
	ID     uint32  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Limit  float32 `protobuf:"fixed32,2,opt,name=Limit" json:"Limit,omitempty"`
	Name   string  `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	UserID int32   `protobuf:"varint,4,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *CategoryRequest) Reset()                    { *m = CategoryRequest{} }
func (m *CategoryRequest) String() string            { return proto.CompactTextString(m) }
func (*CategoryRequest) ProtoMessage()               {}
func (*CategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CategoryRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *CategoryRequest) GetLimit() float32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CategoryRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type CategoryResponse struct {
	ID    uint32  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Limit float32 `protobuf:"fixed32,2,opt,name=Limit" json:"Limit,omitempty"`
	Name  string  `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
}

func (m *CategoryResponse) Reset()                    { *m = CategoryResponse{} }
func (m *CategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*CategoryResponse) ProtoMessage()               {}
func (*CategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CategoryResponse) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *CategoryResponse) GetLimit() float32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CategoryResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CategoryIDRequest struct {
	ID uint32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *CategoryIDRequest) Reset()                    { *m = CategoryIDRequest{} }
func (m *CategoryIDRequest) String() string            { return proto.CompactTextString(m) }
func (*CategoryIDRequest) ProtoMessage()               {}
func (*CategoryIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CategoryIDRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteCategoryResponse struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *DeleteCategoryResponse) Reset()                    { *m = DeleteCategoryResponse{} }
func (m *DeleteCategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCategoryResponse) ProtoMessage()               {}
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteCategoryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*UserPagingRequest)(nil), "UserPagingRequest")
	proto.RegisterType((*ExpensesReponse)(nil), "ExpensesReponse")
	proto.RegisterType((*CategoriesReponse)(nil), "CategoriesReponse")
	proto.RegisterType((*ExpenseRequest)(nil), "ExpenseRequest")
	proto.RegisterType((*ExpenseResponse)(nil), "ExpenseResponse")
	proto.RegisterType((*ExpenseIDRequest)(nil), "ExpenseIDRequest")
	proto.RegisterType((*DeleteExpenseResponse)(nil), "DeleteExpenseResponse")
	proto.RegisterType((*CategoryRequest)(nil), "CategoryRequest")
	proto.RegisterType((*CategoryResponse)(nil), "CategoryResponse")
	proto.RegisterType((*CategoryIDRequest)(nil), "CategoryIDRequest")
	proto.RegisterType((*DeleteCategoryResponse)(nil), "DeleteCategoryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ExpenseService service

type ExpenseServiceClient interface {
	GetExpense(ctx context.Context, in *ExpenseIDRequest, opts ...grpc.CallOption) (*ExpenseResponse, error)
	UpdateExpense(ctx context.Context, in *ExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error)
	RemoveExpense(ctx context.Context, in *ExpenseIDRequest, opts ...grpc.CallOption) (*DeleteExpenseResponse, error)
	GetUserExpenses(ctx context.Context, in *UserPagingRequest, opts ...grpc.CallOption) (*ExpensesReponse, error)
	GetCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	UpdateCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	RemoveCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	GetUserCategories(ctx context.Context, in *UserPagingRequest, opts ...grpc.CallOption) (*CategoriesReponse, error)
}

type expenseServiceClient struct {
	cc *grpc.ClientConn
}

func NewExpenseServiceClient(cc *grpc.ClientConn) ExpenseServiceClient {
	return &expenseServiceClient{cc}
}

func (c *expenseServiceClient) GetExpense(ctx context.Context, in *ExpenseIDRequest, opts ...grpc.CallOption) (*ExpenseResponse, error) {
	out := new(ExpenseResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/GetExpense", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) UpdateExpense(ctx context.Context, in *ExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error) {
	out := new(ExpenseResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/UpdateExpense", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) RemoveExpense(ctx context.Context, in *ExpenseIDRequest, opts ...grpc.CallOption) (*DeleteExpenseResponse, error) {
	out := new(DeleteExpenseResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/RemoveExpense", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) GetUserExpenses(ctx context.Context, in *UserPagingRequest, opts ...grpc.CallOption) (*ExpensesReponse, error) {
	out := new(ExpensesReponse)
	err := grpc.Invoke(ctx, "/ExpenseService/GetUserExpenses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) GetCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	out := new(CategoryResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/GetCategory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) UpdateCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	out := new(CategoryResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/UpdateCategory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) RemoveCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	out := new(DeleteCategoryResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/RemoveCategory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) GetUserCategories(ctx context.Context, in *UserPagingRequest, opts ...grpc.CallOption) (*CategoriesReponse, error) {
	out := new(CategoriesReponse)
	err := grpc.Invoke(ctx, "/ExpenseService/GetUserCategories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ExpenseService service

type ExpenseServiceServer interface {
	GetExpense(context.Context, *ExpenseIDRequest) (*ExpenseResponse, error)
	UpdateExpense(context.Context, *ExpenseRequest) (*ExpenseResponse, error)
	RemoveExpense(context.Context, *ExpenseIDRequest) (*DeleteExpenseResponse, error)
	GetUserExpenses(context.Context, *UserPagingRequest) (*ExpensesReponse, error)
	GetCategory(context.Context, *CategoryIDRequest) (*CategoryResponse, error)
	UpdateCategory(context.Context, *CategoryRequest) (*CategoryResponse, error)
	RemoveCategory(context.Context, *CategoryIDRequest) (*DeleteCategoryResponse, error)
	GetUserCategories(context.Context, *UserPagingRequest) (*CategoriesReponse, error)
}

func RegisterExpenseServiceServer(s *grpc.Server, srv ExpenseServiceServer) {
	s.RegisterService(&_ExpenseService_serviceDesc, srv)
}

func _ExpenseService_GetExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpenseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/GetExpense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetExpense(ctx, req.(*ExpenseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_UpdateExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).UpdateExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/UpdateExpense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).UpdateExpense(ctx, req.(*ExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_RemoveExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpenseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).RemoveExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/RemoveExpense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).RemoveExpense(ctx, req.(*ExpenseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_GetUserExpenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetUserExpenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/GetUserExpenses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetUserExpenses(ctx, req.(*UserPagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetCategory(ctx, req.(*CategoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/UpdateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).UpdateCategory(ctx, req.(*CategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_RemoveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).RemoveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/RemoveCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).RemoveCategory(ctx, req.(*CategoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_GetUserCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetUserCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/GetUserCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetUserCategories(ctx, req.(*UserPagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExpenseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ExpenseService",
	HandlerType: (*ExpenseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExpense",
			Handler:    _ExpenseService_GetExpense_Handler,
		},
		{
			MethodName: "UpdateExpense",
			Handler:    _ExpenseService_UpdateExpense_Handler,
		},
		{
			MethodName: "RemoveExpense",
			Handler:    _ExpenseService_RemoveExpense_Handler,
		},
		{
			MethodName: "GetUserExpenses",
			Handler:    _ExpenseService_GetUserExpenses_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _ExpenseService_GetCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _ExpenseService_UpdateCategory_Handler,
		},
		{
			MethodName: "RemoveCategory",
			Handler:    _ExpenseService_RemoveCategory_Handler,
		},
		{
			MethodName: "GetUserCategories",
			Handler:    _ExpenseService_GetUserCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expense-service/v1/expense-service.proto",
}

func init() { proto.RegisterFile("expense-service/v1/expense-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xb5, 0x9d, 0xa4, 0x2d, 0x53, 0xe5, 0xc3, 0x2b, 0x08, 0x56, 0x4f, 0xd1, 0x72, 0xc9, 0x81,
	0xba, 0x4a, 0x8a, 0x40, 0x48, 0xa0, 0x4a, 0x60, 0x88, 0x22, 0x55, 0x80, 0xb6, 0x2a, 0x12, 0xdc,
	0x4c, 0x98, 0x46, 0x96, 0x9a, 0xd8, 0x78, 0x37, 0x51, 0xc3, 0xaf, 0xe0, 0x4f, 0xf2, 0x3f, 0x90,
	0x77, 0xd7, 0x6b, 0x63, 0x3b, 0x3d, 0xc0, 0x6d, 0xe7, 0x69, 0x76, 0xde, 0xbc, 0xb7, 0x33, 0x0b,
	0x63, 0xbc, 0x4b, 0x70, 0xcd, 0xf1, 0x94, 0x63, 0xba, 0x8d, 0x16, 0x78, 0xb6, 0x9d, 0x9c, 0x55,
	0x20, 0x3f, 0x49, 0x63, 0x11, 0xd3, 0x2f, 0xe0, 0x5e, 0x73, 0x4c, 0x3f, 0x85, 0xcb, 0x68, 0xbd,
	0x64, 0xf8, 0x63, 0x83, 0x5c, 0x90, 0x21, 0x1c, 0x64, 0xe0, 0x3c, 0xf0, 0xec, 0x91, 0x3d, 0xee,
	0x32, 0x1d, 0x65, 0xf8, 0xc7, 0x9b, 0x1b, 0x8e, 0xc2, 0x73, 0x46, 0xf6, 0xb8, 0xc3, 0x74, 0x44,
	0x1e, 0x42, 0xe7, 0x32, 0x5a, 0x45, 0xc2, 0x6b, 0x49, 0x58, 0x05, 0xf4, 0x02, 0xfa, 0xef, 0x14,
	0x27, 0x67, 0x98, 0xc4, 0x6b, 0x8e, 0xe4, 0x29, 0x1c, 0xe5, 0x90, 0x67, 0x8f, 0x5a, 0xe3, 0xe3,
	0xe9, 0xc0, 0xd7, 0x00, 0x43, 0x2e, 0x73, 0x98, 0xc9, 0xa0, 0xef, 0xc1, 0x7d, 0x1b, 0x0a, 0x5c,
	0xc6, 0x69, 0x54, 0x94, 0x98, 0x00, 0x14, 0xa0, 0x2e, 0xe2, 0xfa, 0x1a, 0xda, 0x99, 0x2a, 0xa5,
	0x24, 0xfa, 0xcb, 0x86, 0x9e, 0x61, 0x51, 0x0a, 0x7b, 0xe0, 0x18, 0x75, 0xce, 0x3c, 0x20, 0x04,
	0xda, 0x41, 0x28, 0x50, 0xea, 0x6a, 0x31, 0x79, 0xce, 0x54, 0x7d, 0x0e, 0x6f, 0x37, 0x28, 0x55,
	0x39, 0x4c, 0x05, 0x99, 0x84, 0x9c, 0xcc, 0x6b, 0x8f, 0x6c, 0x29, 0xa1, 0x60, 0x97, 0xd5, 0x99,
	0xc9, 0x28, 0x39, 0xd9, 0x29, 0x3b, 0x49, 0x7f, 0x1a, 0x6f, 0xf2, 0x8e, 0xff, 0xa3, 0xa5, 0xd3,
	0x5a, 0x4b, 0x0d, 0x86, 0x98, 0x14, 0x4a, 0x61, 0xa0, 0xb9, 0xe7, 0xc1, 0x1e, 0x3f, 0xe8, 0x04,
	0x1e, 0x05, 0x78, 0x8b, 0x02, 0xab, 0x5d, 0x7a, 0x70, 0x78, 0xb5, 0x59, 0x2c, 0x90, 0x73, 0x99,
	0x7d, 0xc4, 0xf2, 0x90, 0x2e, 0xa0, 0x5f, 0xf1, 0xa1, 0x26, 0xc9, 0xcc, 0x89, 0xa3, 0xda, 0x97,
	0x41, 0x26, 0xf4, 0x43, 0xb8, 0x52, 0x9a, 0x1e, 0x30, 0x79, 0x2e, 0xf9, 0xd6, 0x56, 0x93, 0xa6,
	0x7d, 0xbb, 0x84, 0x41, 0x55, 0xd9, 0xbf, 0xb3, 0xd0, 0x27, 0x66, 0xc0, 0x76, 0xfb, 0xad, 0x98,
	0xc2, 0x50, 0x59, 0x51, 0x23, 0xde, 0xeb, 0xc5, 0xf4, 0x77, 0xcb, 0x4c, 0xdc, 0x95, 0x5a, 0x37,
	0x72, 0x0e, 0x30, 0x43, 0xa1, 0x41, 0xe2, 0xfa, 0xd5, 0x27, 0x38, 0xa9, 0x6d, 0x02, 0xb5, 0xc8,
	0x33, 0xe8, 0x5e, 0x27, 0xdf, 0x43, 0xf3, 0x0c, 0xa4, 0xef, 0xff, 0x3d, 0xc8, 0x8d, 0xb7, 0x5e,
	0x41, 0x97, 0xe1, 0x2a, 0xde, 0xe2, 0x3d, 0x6c, 0x43, 0xbf, 0xf1, 0x7d, 0xa9, 0x45, 0x5e, 0x42,
	0x7f, 0x86, 0x22, 0xf3, 0x3b, 0x5f, 0x44, 0x42, 0xfc, 0xda, 0x1f, 0x51, 0x10, 0xe7, 0x9b, 0x49,
	0x2d, 0xf2, 0x1c, 0x8e, 0x67, 0x28, 0xcc, 0xf0, 0x13, 0xbf, 0xe6, 0xee, 0x49, 0x7d, 0x32, 0xa9,
	0x45, 0x5e, 0x40, 0x4f, 0xc9, 0x34, 0x57, 0x6b, 0x3b, 0xd5, 0x7c, 0xf1, 0x02, 0x7a, 0x4a, 0xe9,
	0xbd, 0x9c, 0x8f, 0xfd, 0xe6, 0x07, 0xa4, 0x16, 0x79, 0x0d, 0xae, 0x16, 0x5b, 0xfc, 0x17, 0x8d,
	0x72, 0x4d, 0xdd, 0xa8, 0x24, 0xf8, 0xcd, 0xe1, 0xd7, 0x4e, 0x92, 0xc6, 0x77, 0xbb, 0x6f, 0x07,
	0xf2, 0x37, 0x3d, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x84, 0xc7, 0x5f, 0x79, 0x05, 0x00,
	0x00,
}
