// Code generated by protoc-gen-go.
// source: expense-service/v1/expense-service.proto
// DO NOT EDIT!

/*
Package proxy is a generated protocol buffer package.

It is generated from these files:
	expense-service/v1/expense-service.proto

It has these top-level messages:
	UserPagingRequest
	ExpensesResponse
	CategoriesResponse
	CreateExpenseRequest
	UpdateExpenseRequest
	ExpenseResponse
	ExpenseIDRequest
	CreateCategoryRequest
	UpdateCategoryRequest
	CategoryResponse
	CategoryIDRequest
	EmptyResponse
*/
package proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserPagingRequest struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=Offset" json:"Offset,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=Limit" json:"Limit,omitempty"`
}

func (m *UserPagingRequest) Reset()                    { *m = UserPagingRequest{} }
func (m *UserPagingRequest) String() string            { return proto.CompactTextString(m) }
func (*UserPagingRequest) ProtoMessage()               {}
func (*UserPagingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserPagingRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserPagingRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *UserPagingRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ExpensesResponse struct {
	Expenses []*ExpenseResponse `protobuf:"bytes,1,rep,name=Expenses" json:"Expenses,omitempty"`
}

func (m *ExpensesResponse) Reset()                    { *m = ExpensesResponse{} }
func (m *ExpensesResponse) String() string            { return proto.CompactTextString(m) }
func (*ExpensesResponse) ProtoMessage()               {}
func (*ExpensesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExpensesResponse) GetExpenses() []*ExpenseResponse {
	if m != nil {
		return m.Expenses
	}
	return nil
}

type CategoriesResponse struct {
	Categories []*CategoryResponse `protobuf:"bytes,1,rep,name=Categories" json:"Categories,omitempty"`
}

func (m *CategoriesResponse) Reset()                    { *m = CategoriesResponse{} }
func (m *CategoriesResponse) String() string            { return proto.CompactTextString(m) }
func (*CategoriesResponse) ProtoMessage()               {}
func (*CategoriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CategoriesResponse) GetCategories() []*CategoryResponse {
	if m != nil {
		return m.Categories
	}
	return nil
}

type CreateExpenseRequest struct {
	Date       int64   `protobuf:"varint,2,opt,name=Date" json:"Date,omitempty"`
	Value      float32 `protobuf:"fixed32,3,opt,name=Value" json:"Value,omitempty"`
	CategoryID string  `protobuf:"bytes,4,opt,name=CategoryID" json:"CategoryID,omitempty"`
	UserID     string  `protobuf:"bytes,5,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *CreateExpenseRequest) Reset()                    { *m = CreateExpenseRequest{} }
func (m *CreateExpenseRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateExpenseRequest) ProtoMessage()               {}
func (*CreateExpenseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateExpenseRequest) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *CreateExpenseRequest) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CreateExpenseRequest) GetCategoryID() string {
	if m != nil {
		return m.CategoryID
	}
	return ""
}

func (m *CreateExpenseRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UpdateExpenseRequest struct {
	ID         string  `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Date       int64   `protobuf:"varint,2,opt,name=Date" json:"Date,omitempty"`
	Value      float32 `protobuf:"fixed32,3,opt,name=Value" json:"Value,omitempty"`
	CategoryID string  `protobuf:"bytes,4,opt,name=CategoryID" json:"CategoryID,omitempty"`
	UserID     string  `protobuf:"bytes,5,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *UpdateExpenseRequest) Reset()                    { *m = UpdateExpenseRequest{} }
func (m *UpdateExpenseRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateExpenseRequest) ProtoMessage()               {}
func (*UpdateExpenseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateExpenseRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateExpenseRequest) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *UpdateExpenseRequest) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *UpdateExpenseRequest) GetCategoryID() string {
	if m != nil {
		return m.CategoryID
	}
	return ""
}

func (m *UpdateExpenseRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type ExpenseResponse struct {
	ID         string  `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Date       int64   `protobuf:"varint,2,opt,name=Date" json:"Date,omitempty"`
	Value      float32 `protobuf:"fixed32,3,opt,name=Value" json:"Value,omitempty"`
	CategoryID string  `protobuf:"bytes,4,opt,name=CategoryID" json:"CategoryID,omitempty"`
}

func (m *ExpenseResponse) Reset()                    { *m = ExpenseResponse{} }
func (m *ExpenseResponse) String() string            { return proto.CompactTextString(m) }
func (*ExpenseResponse) ProtoMessage()               {}
func (*ExpenseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ExpenseResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ExpenseResponse) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *ExpenseResponse) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *ExpenseResponse) GetCategoryID() string {
	if m != nil {
		return m.CategoryID
	}
	return ""
}

type ExpenseIDRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *ExpenseIDRequest) Reset()                    { *m = ExpenseIDRequest{} }
func (m *ExpenseIDRequest) String() string            { return proto.CompactTextString(m) }
func (*ExpenseIDRequest) ProtoMessage()               {}
func (*ExpenseIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ExpenseIDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type CreateCategoryRequest struct {
	Limit  float32 `protobuf:"fixed32,2,opt,name=Limit" json:"Limit,omitempty"`
	Name   string  `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	UserID string  `protobuf:"bytes,4,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *CreateCategoryRequest) Reset()                    { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()               {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateCategoryRequest) GetLimit() float32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CreateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCategoryRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UpdateCategoryRequest struct {
	ID     string  `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Limit  float32 `protobuf:"fixed32,2,opt,name=Limit" json:"Limit,omitempty"`
	Name   string  `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	UserID string  `protobuf:"bytes,4,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *UpdateCategoryRequest) Reset()                    { *m = UpdateCategoryRequest{} }
func (m *UpdateCategoryRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateCategoryRequest) ProtoMessage()               {}
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateCategoryRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateCategoryRequest) GetLimit() float32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UpdateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCategoryRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type CategoryResponse struct {
	ID    string  `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Limit float32 `protobuf:"fixed32,2,opt,name=Limit" json:"Limit,omitempty"`
	Name  string  `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
}

func (m *CategoryResponse) Reset()                    { *m = CategoryResponse{} }
func (m *CategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*CategoryResponse) ProtoMessage()               {}
func (*CategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CategoryResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CategoryResponse) GetLimit() float32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CategoryResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CategoryIDRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *CategoryIDRequest) Reset()                    { *m = CategoryIDRequest{} }
func (m *CategoryIDRequest) String() string            { return proto.CompactTextString(m) }
func (*CategoryIDRequest) ProtoMessage()               {}
func (*CategoryIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CategoryIDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type EmptyResponse struct {
}

func (m *EmptyResponse) Reset()                    { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()               {}
func (*EmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*UserPagingRequest)(nil), "UserPagingRequest")
	proto.RegisterType((*ExpensesResponse)(nil), "ExpensesResponse")
	proto.RegisterType((*CategoriesResponse)(nil), "CategoriesResponse")
	proto.RegisterType((*CreateExpenseRequest)(nil), "CreateExpenseRequest")
	proto.RegisterType((*UpdateExpenseRequest)(nil), "UpdateExpenseRequest")
	proto.RegisterType((*ExpenseResponse)(nil), "ExpenseResponse")
	proto.RegisterType((*ExpenseIDRequest)(nil), "ExpenseIDRequest")
	proto.RegisterType((*CreateCategoryRequest)(nil), "CreateCategoryRequest")
	proto.RegisterType((*UpdateCategoryRequest)(nil), "UpdateCategoryRequest")
	proto.RegisterType((*CategoryResponse)(nil), "CategoryResponse")
	proto.RegisterType((*CategoryIDRequest)(nil), "CategoryIDRequest")
	proto.RegisterType((*EmptyResponse)(nil), "EmptyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ExpenseService service

type ExpenseServiceClient interface {
	GetExpense(ctx context.Context, in *ExpenseIDRequest, opts ...grpc.CallOption) (*ExpenseResponse, error)
	CreateExpense(ctx context.Context, in *CreateExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error)
	UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error)
	RemoveExpense(ctx context.Context, in *ExpenseIDRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetUserExpenses(ctx context.Context, in *UserPagingRequest, opts ...grpc.CallOption) (*ExpensesResponse, error)
	GetCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	RemoveCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetUserCategories(ctx context.Context, in *UserPagingRequest, opts ...grpc.CallOption) (*CategoriesResponse, error)
}

type expenseServiceClient struct {
	cc *grpc.ClientConn
}

func NewExpenseServiceClient(cc *grpc.ClientConn) ExpenseServiceClient {
	return &expenseServiceClient{cc}
}

func (c *expenseServiceClient) GetExpense(ctx context.Context, in *ExpenseIDRequest, opts ...grpc.CallOption) (*ExpenseResponse, error) {
	out := new(ExpenseResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/GetExpense", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) CreateExpense(ctx context.Context, in *CreateExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error) {
	out := new(ExpenseResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/CreateExpense", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, opts ...grpc.CallOption) (*ExpenseResponse, error) {
	out := new(ExpenseResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/UpdateExpense", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) RemoveExpense(ctx context.Context, in *ExpenseIDRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/RemoveExpense", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) GetUserExpenses(ctx context.Context, in *UserPagingRequest, opts ...grpc.CallOption) (*ExpensesResponse, error) {
	out := new(ExpensesResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/GetUserExpenses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) GetCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	out := new(CategoryResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/GetCategory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	out := new(CategoryResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/CreateCategory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	out := new(CategoryResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/UpdateCategory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) RemoveCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/RemoveCategory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) GetUserCategories(ctx context.Context, in *UserPagingRequest, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	out := new(CategoriesResponse)
	err := grpc.Invoke(ctx, "/ExpenseService/GetUserCategories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ExpenseService service

type ExpenseServiceServer interface {
	GetExpense(context.Context, *ExpenseIDRequest) (*ExpenseResponse, error)
	CreateExpense(context.Context, *CreateExpenseRequest) (*ExpenseResponse, error)
	UpdateExpense(context.Context, *UpdateExpenseRequest) (*ExpenseResponse, error)
	RemoveExpense(context.Context, *ExpenseIDRequest) (*EmptyResponse, error)
	GetUserExpenses(context.Context, *UserPagingRequest) (*ExpensesResponse, error)
	GetCategory(context.Context, *CategoryIDRequest) (*CategoryResponse, error)
	CreateCategory(context.Context, *CreateCategoryRequest) (*CategoryResponse, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*CategoryResponse, error)
	RemoveCategory(context.Context, *CategoryIDRequest) (*EmptyResponse, error)
	GetUserCategories(context.Context, *UserPagingRequest) (*CategoriesResponse, error)
}

func RegisterExpenseServiceServer(s *grpc.Server, srv ExpenseServiceServer) {
	s.RegisterService(&_ExpenseService_serviceDesc, srv)
}

func _ExpenseService_GetExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpenseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/GetExpense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetExpense(ctx, req.(*ExpenseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_CreateExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).CreateExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/CreateExpense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).CreateExpense(ctx, req.(*CreateExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_UpdateExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).UpdateExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/UpdateExpense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).UpdateExpense(ctx, req.(*UpdateExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_RemoveExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpenseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).RemoveExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/RemoveExpense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).RemoveExpense(ctx, req.(*ExpenseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_GetUserExpenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetUserExpenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/GetUserExpenses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetUserExpenses(ctx, req.(*UserPagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetCategory(ctx, req.(*CategoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/CreateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/UpdateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_RemoveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).RemoveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/RemoveCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).RemoveCategory(ctx, req.(*CategoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_GetUserCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).GetUserCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExpenseService/GetUserCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).GetUserCategories(ctx, req.(*UserPagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExpenseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ExpenseService",
	HandlerType: (*ExpenseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExpense",
			Handler:    _ExpenseService_GetExpense_Handler,
		},
		{
			MethodName: "CreateExpense",
			Handler:    _ExpenseService_CreateExpense_Handler,
		},
		{
			MethodName: "UpdateExpense",
			Handler:    _ExpenseService_UpdateExpense_Handler,
		},
		{
			MethodName: "RemoveExpense",
			Handler:    _ExpenseService_RemoveExpense_Handler,
		},
		{
			MethodName: "GetUserExpenses",
			Handler:    _ExpenseService_GetUserExpenses_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _ExpenseService_GetCategory_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _ExpenseService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _ExpenseService_UpdateCategory_Handler,
		},
		{
			MethodName: "RemoveCategory",
			Handler:    _ExpenseService_RemoveCategory_Handler,
		},
		{
			MethodName: "GetUserCategories",
			Handler:    _ExpenseService_GetUserCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expense-service/v1/expense-service.proto",
}

func init() { proto.RegisterFile("expense-service/v1/expense-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x9d, 0xa4, 0xd0, 0xa9, 0xe2, 0xc4, 0x43, 0x12, 0x59, 0x39, 0xa0, 0x68, 0xb9, 0xe4,
	0x00, 0x5b, 0xb5, 0x45, 0x3d, 0x20, 0x81, 0x10, 0x75, 0x15, 0x45, 0xaa, 0x00, 0x19, 0x15, 0xa9,
	0xdc, 0x0c, 0x4c, 0x23, 0x0b, 0x12, 0x1b, 0x7b, 0x1b, 0x25, 0xff, 0x80, 0x3f, 0xc9, 0x7f, 0x41,
	0xde, 0x75, 0x36, 0xfe, 0x4a, 0x0f, 0x20, 0xb8, 0x79, 0x9f, 0x76, 0xe6, 0xcd, 0x7b, 0x33, 0x3b,
	0x86, 0x09, 0xad, 0x23, 0x5a, 0x26, 0xf4, 0x2c, 0xa1, 0x78, 0x15, 0x7c, 0xa1, 0xe3, 0xd5, 0xc9,
	0x71, 0x09, 0xe2, 0x51, 0x1c, 0x8a, 0x90, 0xdd, 0x80, 0x7d, 0x9d, 0x50, 0xfc, 0xde, 0x9f, 0x07,
	0xcb, 0xb9, 0x47, 0x3f, 0xee, 0x28, 0x11, 0x38, 0x84, 0x83, 0x14, 0x9c, 0xb9, 0x8e, 0x31, 0x36,
	0x26, 0x87, 0x5e, 0x76, 0x4a, 0xf1, 0x77, 0xb7, 0xb7, 0x09, 0x09, 0xc7, 0x1c, 0x1b, 0x93, 0xb6,
	0x97, 0x9d, 0xb0, 0x0f, 0xed, 0xab, 0x60, 0x11, 0x08, 0xa7, 0x29, 0x61, 0x75, 0x60, 0xaf, 0xa1,
	0x77, 0xa9, 0x38, 0x13, 0x8f, 0x92, 0x28, 0x5c, 0x26, 0x84, 0x4f, 0xe1, 0xe1, 0x16, 0x73, 0x8c,
	0x71, 0x73, 0x72, 0x74, 0xda, 0xe3, 0x19, 0xb0, 0xbd, 0xe3, 0xe9, 0x1b, 0x6c, 0x0a, 0x78, 0xe1,
	0x0b, 0x9a, 0x87, 0x71, 0x90, 0xcb, 0x71, 0x02, 0xb0, 0x43, 0xb3, 0x2c, 0x36, 0xcf, 0xa0, 0x8d,
	0x4e, 0x93, 0xbb, 0xc4, 0xd6, 0xd0, 0xbf, 0x88, 0xc9, 0x17, 0xa4, 0xb9, 0x94, 0x50, 0x84, 0x96,
	0xeb, 0x0b, 0x92, 0x72, 0x9a, 0x9e, 0xfc, 0x4e, 0xc5, 0x7c, 0xf4, 0xbf, 0xdf, 0x91, 0x14, 0x63,
	0x7a, 0xea, 0x80, 0x8f, 0x35, 0xe9, 0x66, 0xe6, 0x3a, 0x2d, 0x69, 0x4b, 0x0e, 0xc9, 0x59, 0xd6,
	0xce, 0x5b, 0xc6, 0x7e, 0x1a, 0xd0, 0xbf, 0x8e, 0xbe, 0x56, 0xa9, 0x2d, 0x30, 0xb5, 0xbf, 0xe6,
	0xcc, 0xfd, 0x0f, 0xa5, 0x7c, 0x83, 0x6e, 0xc9, 0xea, 0x7f, 0x57, 0x04, 0x63, 0xba, 0xf9, 0x33,
	0x77, 0x8f, 0x64, 0x76, 0x03, 0x03, 0xd5, 0x95, 0x5d, 0xef, 0xd4, 0x45, 0x3d, 0x4f, 0xa6, 0xa2,
	0x94, 0x87, 0xb4, 0xb8, 0xb7, 0xfe, 0x42, 0xd5, 0x71, 0xe8, 0xc9, 0xef, 0x9c, 0xd6, 0x56, 0x41,
	0x6b, 0x00, 0x03, 0xe5, 0x7a, 0x39, 0x75, 0x59, 0xf1, 0xdf, 0x53, 0x5d, 0x41, 0xaf, 0x3c, 0x7b,
	0x7f, 0xce, 0xc2, 0x9e, 0x80, 0xbd, 0x73, 0x71, 0x9f, 0x71, 0x5d, 0xe8, 0x5c, 0x2e, 0x22, 0xa1,
	0xf9, 0x4e, 0x7f, 0xb5, 0xc0, 0xca, 0xec, 0xfe, 0xa0, 0x9e, 0x37, 0x9e, 0x01, 0x4c, 0x49, 0x64,
	0x20, 0xda, 0xbc, 0xdc, 0x8d, 0x51, 0xe5, 0xe1, 0xb1, 0x06, 0xbe, 0x80, 0x4e, 0xe1, 0x9d, 0xe0,
	0x80, 0xd7, 0xbd, 0x9b, 0x7d, 0xb1, 0x85, 0x41, 0xc7, 0x01, 0xaf, 0x1b, 0xfc, 0xda, 0xd8, 0xe7,
	0xd0, 0xf1, 0x68, 0x11, 0xae, 0xe8, 0x9e, 0x7a, 0x2d, 0x5e, 0xd0, 0x2c, 0x19, 0xbb, 0x53, 0x12,
	0x69, 0x1b, 0xb6, 0x1b, 0x03, 0x91, 0x57, 0xb6, 0xd9, 0x48, 0xe7, 0x4a, 0x72, 0xb1, 0xe7, 0x70,
	0x34, 0x25, 0xb1, 0xb5, 0x1a, 0x91, 0x57, 0x5c, 0x1f, 0x55, 0x77, 0x0a, 0x6b, 0xe0, 0x4b, 0xb0,
	0x8a, 0x33, 0x8b, 0x43, 0x5e, 0x3b, 0xc4, 0x7b, 0xc3, 0x8b, 0x73, 0x89, 0x43, 0x5e, 0x3b, 0xa8,
	0xf5, 0xe1, 0xe7, 0x60, 0x29, 0x9f, 0xee, 0x2d, 0xbc, 0xea, 0xd4, 0x2b, 0xb0, 0x33, 0xa7, 0x76,
	0x4b, 0xb1, 0xd6, 0xab, 0x47, 0xbc, 0xba, 0x70, 0x59, 0xe3, 0xcd, 0x83, 0x4f, 0xed, 0x28, 0x0e,
	0xd7, 0x9b, 0xcf, 0x07, 0xf2, 0xaf, 0x71, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x16, 0x62, 0x02,
	0xb2, 0x61, 0x06, 0x00, 0x00,
}
