FROM golang

RUN go get github.com/jinzhu/gorm && \
    go get google.golang.org/grpc && \
    go get github.com/dgrijalva/jwt-go && \
    go get github.com/Sirupsen/logrus && \
    go get golang.org/x/time/rate && \
    go get github.com/gorilla/mux && \
    go get github.com/satori/go.uuid && \ 
    go get golang.org/x/crypto/bcrypt && \
    go get github.com/jinzhu/gorm/dialects/postgres && \
    go get github.com/gkarlik/quark-go && \
    go get -d github.com/gkarlik/expense-tracker/shared
    
COPY . /go/src/github.com/gkarlik/expense-tracker/user-service
WORKDIR /go/src/github.com/gkarlik/expense-tracker/user-service

ENV USER_SERVICE_NAME=UserService \
    USER_SERVICE_VERSION=v1 \
    USER_SERVICE_PORT=6666 \
    DISCOVERY=http://api-gateway:8888 \
    DATABASE_DIALECT=postgres \
    DATABASE="host=database user=postgres dbname=user_service sslmode=disable password=" \
    UPGRADE_DATABASE=1

ENTRYPOINT go run main.go